server:
  port: 8877


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order-module
# 添加负载均衡策略 RandomRule（随机，默认策略） RoundRobinRule（轮询） BestAvailableRule（最小并发）
PRODUCT-MODULE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule


