server:
  port: 8877

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: order-module
  main:
    allow-bean-definition-overriding: true
  redis:
    database: 0
    host: 192.168.19.10
    port: 6379
    timeout: 2000ms
    password: 123
  zipkin:
    base-url: http://192.168.19.10:9411/
  sleuth:
    sampler:
      probability: 1

# 添加负载均衡策略 RandomRule（随机，默认策略） RoundRobinRule（轮询） BestAvailableRule（最小并发）
PRODUCT-MODULE:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"