server:
  port: 8874


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: product-module
  zipkin:
    base-url: http://192.168.19.10:9411/
  sleuth:
    sampler:
      probability: 1


